spring.application.name=Lab3-SpringBoot

app.notification.channel=email
app.notification.from=no-reply@lab.com
app.notification.max-retries=3
app.notification.enabled=true

# Doi thanh "dev" hoac "prod" de kich hoat profile tuong ung
spring.profiles.active=dev
